server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/template?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: yfyfyf123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 10.135.37.134
      port: 6379
      password: yfyfyf
